# openjdk
brew "openjdk"

# essentials
brew "asciinema"
cask "claude-code"
brew "ctags"
brew "curl"
cask "ghostty"
brew "fish"
brew "fzf"
brew "git"
brew "go"
brew "golangci-lint"
brew "jj"
brew "lua"
brew "marp-cli"
brew "nmap"
brew "neovim"
brew "openssl"
brew "rbenv"
brew "ripgrep"
brew "ruby-build"
brew "rustup"
brew "ssh-copy-id"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "xsel"

# personal packages (deployed to ~/Brewfile.personal by sync.sh)
require "~/Brewfile.personal" if File.exist? "~/Brewfile.personal"

