#! /bin/bash

set -x

cd $(dirname "${0}")

rsync_options=(-av --recursive --itemize-changes)

src="homedir/"
tgt="${HOME}"
personal=1
mode="forward"

while getopts "uw" arg; do
  case "${arg}" in
    w)
      personal=0
      ;;
    u)
      t=$(mktemp)
      find homedir -type f | cut -d/ -f2- > $t

      rsync_options+=(--update --files-from=${t})

      src="${HOME}/"
      tgt="homedir"
      mode="reverse"

      ;;
    *)
      echo "usage: $(basename ${0}) [-u] [-w]"
      exit 1
      ;;
  esac
done

rsync "${rsync_options[@]}" "${src}" "${tgt}"

if [ "${mode}" = "forward" ]; then
  {
    echo "# generated by sync.sh -- do not edit"
    echo
    cat Brewfile
    if [ "${personal}" = "1" ]; then
      echo
      cat Brewfile.personal
    fi
  } > "${HOME}/Brewfile"
fi
