- name: tap additional brew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/fonts
    - neovim/neovim
    - koekeishiya/formulae
- name: brew update and cleanup
  shell: brew update && brew cleanup
- name: install openjdk
  homebrew_cask:
    state: latest
    name: adoptopenjdk
- name: install essentials
  homebrew:
    state: latest
    name:
      - awscli
      - ctags
      - curl
      - duplicity
      - fish
      - fzf
      - git
      - leiningen
      - maven
      - mobile-shell
      - nmap
      - openssl
      - packer
      - rbenv
      - reattach-to-user-namespace
      - ruby-build
      - skhd
      - ssh-copy-id
      - the_silver_searcher
      - terraform
      - tmux
      - tree
      - unrar
      - watch
      - wget
      - yabai
      - zsh
- name: install fonts
  homebrew_cask:
    state: present
    name:
      - font-hack
      - font-iosevka
      - font-source-code-pro
- name: install core casks
  homebrew_cask:
    state: present
    name:
      - flux
      - kitty
- name: install neovim
  homebrew:
    state: head
    name: neovim
