- name: tap additional brew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/binary
    - homebrew/dupes
    - caskroom/fonts
    - neovim/neovim
    - crisidev/homebrew-chunkwm
- name: brew update and cleanup
  shell: brew update && brew cleanup
- name: install essentials
  homebrew: name={{ item }} state=latest
  with_items:
    - awscli
    - chunkwm
    - ctags
    - curl
    - duplicity
    - fish
    - fzf
    - leiningen
    - maven
    - mobile-shell
    - nmap
    - openssl
    - packer
    - rbenv
    - reattach-to-user-namespace
    - ruby-build
    - skhd
    - ssh-copy-id
    - the_silver_searcher
    - terraform
    - tmux
    - tree
    - unrar
    - watch
    - wget
    - zsh
- name: install fonts
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-hack
    - font-iosevka
    - font-source-code-pro
- name: install core casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - dropbox
    - flux
    - google-drive
    - iterm2
- name: install git
  homebrew: name=git state=latest install_options=with-brewed-curl,with-brewed-openssl
- name: install neovim
  homebrew: name=neovim state=head
