- name: synchronizes homedir
  synchronize: src=../homedir/ dest=~ dirs=yes
- name: symlink .vim for neovim
  file: path=~/.config/nvim src=~/.vim state=link
- name: symlink .vimrc for neovim
  file: path=~/.config/nvim/init.vim src=~/.vimrc state=link
